### PR TITLE
Fix augmentation of StringMatrix

### PR DESCRIPTION
**Pull request by gronostajo**
Fixes augmentation of string matrices in the builder. Also adds a test case.

Currently the builder always augments the matrix with objects and the `StringContainer::forValue` method fails because its argument is required to be a string.

### CODE REVIEW

**Comment by CerebralFart** [comment]
Hi gronostajo,
Thanks for your contribution, I hope to be able to review it next week.
To make the review process a little easier for me, could you provide a small sample illustrating what went wrong before?

**Comment by gronostajo** [comment]
Hi @CerebralFart. I think the problem is best illustrated by the unit test I've added - it wouldn't pass with before my changes.

Basically when string labels are used, they're passed to `StringContainer::forValue` when building a matrix. That method is annotated to accept only string arguments.

If the matrix is not square, it will be augmented with objects of the `Marker` class. These objects will be passed to `StringContainer::forValue` too and PHP will error out, because that method expects strings.

**Comment by CerebralFart** [comment]
Ah yes, that's clearly an oversight on my part. Thanks for contributing a test case.

However, using magic values doesn't seem to me to be the right way to go about solving this. I think it might be cleaner to change how the labels are handled in the StringMatrix constructor (ensuring `forValue` isn't called on markers.) That way, we can keep checking if something is a marker using a simple `instanceof`, and there's no risk of accidental naming collisions

**Comment by CerebralFart** [comment]
I think I've been able to implement what you were after on the [`fix-string-augmentation`-branch](https://github.com/Kick-In/hungarian/tree/fix-string-augmentation). Could you check if this indeed works with your use-case? If it does, I'll be publishing it as 0.2.0.

Thanks once again for your contributions!

**Comment by gronostajo** [comment]
This works great and it's much cleaner than my attempt. Thanks for getting this fixed.

**Comment by CerebralFart** [comment]
No problem, thanks for pointing out this bug. Version 0.2.0 is now available in composer.

**Pull request closed without merging**
